name: CI

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

permissions:
  contents: read

jobs:
  ubuntu-ninja-clang:
    name: Ubuntu (ninja, clang)
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare
        run: |
          sudo apt update
          sudo apt install ninja-build
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Build and run tests
        env:
          CC: clang
          CXX: clang++
        run: |
          scripts/test.sh

  ubuntu-make-gcc:
    name: Ubuntu (make, gcc)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Build and run tests
        env:
          CC: gcc
          CXX: g++
        run: |
          scripts/initbuild.sh make
          scripts/test.sh

  macos:
    name: macOS
    runs-on: macos-12
    steps:
      - name: Prepare
        run: |
          brew install cmake ninja
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Build and run tests
        run: |
          scripts/test.sh

  windows:
    name: Windows
    runs-on: windows-2022
    steps:
      - uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Build and run tests
        run: |
          cmake .
          msbuild FlatCC.sln /m /property:Configuration=Release
          ctest -VV
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            flatcc/bin/Release/flatcc.exe
